#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libsass
Version  : 3.5.2
Release  : 1
URL      : https://github.com/sass/libsass/archive/3.5.2.tar.gz
Source0  : https://github.com/sass/libsass/archive/3.5.2.tar.gz
Summary  : A C/C++ implementation of a Sass compiler
Group    : Development/Tools
License  : MIT
Patch1: build.patch

%description
LibSass is a C/C++ port of the Sass engine. The point is to be simple, fast, and easy to integrate.

%prep
%setup -q -n libsass-3.5.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522195641
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1522195641
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
